version: "3.8"

services:
  base:
    image: ghcr.io/ahayden/toolbox:base
    hostname: base
    extra_hosts:
      - "base:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    command: /bin/bash 

  dev:
    image: ghcr.io/ahayden/toolbox:dev
    hostname: dev
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "dev:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/$USER/persist
      - $HOME/src:/home/$USER/src
    command: /bin/bash -l

  sci:
    image: ghcr.io/ahayden/toolbox:sci
    hostname: sci
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "sci:127.0.0.1"
    network_mode: host
    container_name: sci
    volumes:
      - home-persist:/home/$USER/persist
      - $HOME/src:/home/$USER/src

volumes:
  home-persist:
