version: "3.8"

services:
  base:
    image: ghcr.io/ahayden/toolbox:base
    hostname: base
    extra_hosts:
      - "base:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    command: /bin/bash 

  user:
    image: ghcr.io/ahayden/toolbox:user
    hostname: user
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "user:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/ahayden/persist
    command: /bin/bash -l

  dev:
    image: ghcr.io/ahayden/toolbox:dev
    hostname: dev
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "dev:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/ahayden/persist
    command: /bin/bash -l

  jupyter:
    image: ghcr.io/ahayden/toolbox:jupyter
    hostname: jupyter
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "jupyter:127.0.0.1"
    network_mode: host
    container_name: jupyter
    volumes:
      - home-persist:/home/ahayden/persist

volumes:
  home-persist:
