version: "3.8"

services:
  base:
    image: ahayden/toolbox:base
    build:
      context: .
      dockerfile: ./Dockerfile.base
    hostname: base
    extra_hosts:
      - "base:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    command: /bin/bash

  user:
    image: ahayden/toolbox:user
    build:
      context: .
      dockerfile: ./Dockerfile.user
    hostname: user
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "user:127.0.0.1"
    restart: unless-stopped
    network_mode: host
    volumes:
      - home-persist:/home/ahayden/persist
    command: /bin/bash

volumes:
  home-persist:
