ARG source_repo
FROM ${source_repo}:user

ARG container_user
RUN test -n "${container_user}"

USER root

# hadolint ignore=DL3008
RUN apt-get update -qq -y && apt-get install --no-install-recommends -qq -y \
        python3 python3-pip python3-dev python3-setuptools \
        r-base golang gcc jq xxd ruby ruby-dev make man-db \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

# hadolint ignore=DL3028
RUN gem install travis --no-document

COPY init.sh /home/${container_user}/.local/bin/init.sh

USER ${container_user}

