ARG source_repo
FROM ${source_repo}:dev

ARG container_user
RUN test -n "${container_user}"

USER root

RUN apt-get update -qq -y && apt-get install --no-install-recommends -qq -y \
        texlive texlive-plain-generic texlive-latex-extra texlive-xetex \ 
	lmodern pandoc librsvg2-bin aspell fonts-freefont-ttf \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

USER ${container_user}

