version: "3.8"

services:
  dev:
    image: ghcr.io/ahayden/toolbox:dev
    hostname: dev
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "dev:127.0.0.1"
    ports:
      - "2222:22"
    container_name: dev
    volumes:
      - home-persist:/home/$USER/persist
    command: sudo /usr/sbin/sshd -D -e

  sci:
    image: ghcr.io/ahayden/toolbox:sci
    hostname: sci
    environment:
      TERM: "xterm-color"
    extra_hosts:
      - "sci:127.0.0.1"
    container_name: sci
    volumes:
      - home-persist:/home/$USER/persist

volumes:
  home-persist:
