ARG source_repo
FROM ${source_repo}:base

ARG container_user
RUN test -n "${container_user}"

USER root

# Enable shell pipefail option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /tmp

RUN apt-get update -qq -y && apt-get install --no-install-recommends -qq -y \
        python3 python3-pip python3-dev python3-setuptools awscli \
        golang gcc g++ jq xxd ruby ruby-dev make man-db \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN gem install travis --no-document

RUN python3 -m pip install pre-commit

RUN curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin-amd64.deb" \
    && dpkg -i session-manager-plugin-amd64.deb ; exit 0 #ignore error

RUN curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" -o "session-manager-plugin-arm64.deb" \
    && dpkg -i session-manager-plugin-arm64.deb ; exit 0 #ignore error

# set links to persistent user environment
RUN su - ${container_user} -c "cd && \
    mkdir -p persist/.ssh && ln -s persist/.ssh . ; \
    mkdir -p persist/.config && ln -s persist/.config . ; \
    mkdir -p persist/.aws && ln -s persist/.aws ."

WORKDIR /home/${container_user}

USER ${container_user}

RUN echo 'eval `ssh-agent -s`; [ -f ~/.ssh/github ] && ssh-add ~/.ssh/github' > git-init

CMD ["/bin/bash","-l"]
