name: test 

on:
  push:
    branches:
#     - main
      - none

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/hadolint/hadolint:latest
    strategy:
      matrix:
        container: [ 'base', 'user', 'dev', 'jupyter' ]
    steps:
    - uses: actions/checkout@v2
    - name: Run hadolint
      run: hadolint
        ./Dockerfile.${{ matrix.container }}

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate docker-compose.yaml 
      run: docker-compose -f docker-compose.yaml config

